boxyhq/saas-starter-kit

Procfile
README.md
app.json

This Pull request adds the `Deploy to Heroku` button in the Readme.md  of the project.

Create a 'Deploy to Heroku' Button

---

.do/deploy.template.yaml
README.md

This Pull request adds the `Deploy to DigitalOcean` button in the Readme.md of the project.

 Add a 'Deploy to DigitalOcean' Button

---

lib/email/sendWelcomeEmail.ts
pages/api/auth/join.ts

This Pull request adds a simple welcome email template. This welcome email will be immediately sent to the user after successfully signed up.
Resolves #10

Email notification after signup

---

.env.example
README.md
docker-compose.yml
package-lock.json
package.json

I add a docker compose file to the project and update the readme to make more easy for the beginners run the database. With this PR they only need to install docker compose and run `docker-compose up -d` no need to install db or search for how to do this.
PS: i leave a example how to build a url for postgres

Config docker to run local more easy

---

.github/dependabot.yml

Enable dependabot alerts following the example provided in the issue
Resolves #46

Enable dependabot alerts

---

components/interfaces/SAML/ConfigureSAML.tsx
hooks/useSAMLConfig.ts
lib/jackson.ts
package-lock.json
package.json
pages/api/auth/sso/index.ts
pages/api/teams/[slug]/saml.ts
pages/auth/sso.tsx

Upgrade the SAML Jackson

---

README.md

Added Saas starter kit blog link

Added blog link

---

components/interfaces/Auth/Join.tsx
components/interfaces/Team/TeamNav.tsx
components/interfaces/Team/TeamTab.tsx
components/layouts/AccountLayout.tsx
components/layouts/AuthLayout.tsx
components/ui/NavItem.tsx
components/ui/Navbar.tsx
components/ui/Sidebar.tsx
lib/app.ts
lib/teams.ts
locales/en/common.json
pages/teams/[slug]/audit-logs.tsx
pages/teams/[slug]/directory-sync.tsx
pages/teams/[slug]/members.tsx
pages/teams/[slug]/saml.tsx
pages/teams/[slug]/settings.tsx
pages/teams/[slug]/webhooks.tsx

- Update the sidebar and icons
- Read the brand name and logo from the app.ts
- Add Sign Out button to the header
- Update some texts
- Remove the team tab from the pages
- Update translation

Update sidebar and fix the icons

---

lib/email/sendEmail.ts
lib/svix.ts
package-lock.json

Iif email or webhook details are not specified skip operations instead of crashing with an error

Skip webhook or email op if env vars not defined

---

components/account/ProfileImageUpload.tsx
components/account/UpdateAccount.tsx
locales/en/common.json

- When a photo is present, the remove photo button is visible
- When the remove photo button is clicked, it removes the present image 
- remove-photo: "Remove Photo" added in common.json file

417 update account/optional profile image

---

CONTRIBUTING.md
README.md

Closes #593 
I've made the necessary changes to the Setup step in both the README.md and CONTRIBUTING.md files, as specified in the issue.

docs: Update Setup step

---

components/apiKey/APIKeys.tsx
components/auth/GithubButton.tsx
components/auth/GoogleButton.tsx
components/auth/Join.tsx
components/auth/JoinWithInvitation.tsx
components/team/Teams.tsx
lib/env.ts
lib/metrics.ts
locales/en/common.json
package-lock.json
package.json
pages/api/auth/[...nextauth].ts
pages/api/users.ts
pages/auth/forgot-password.tsx
pages/auth/join.tsx
pages/auth/login.tsx
pages/auth/magic-link.tsx
pages/auth/sso/index.tsx
pages/dashboard.tsx
pages/invitations/[token].tsx
pages/teams/[slug]/saml.tsx

- Refactored the join via invite link flow.
- Fixed the redirect issue after login.
- Consolidated redirect path.
- Removed the roles property from the session. We're no longer using it.
- Add request validation to `/api/users` endpoint. 
- Handle loading state while fetching session.
- Remove react-icons

Fix the redirect issues

---

README.md

add contributors into readme

---

.husky/pre-commit
package-lock.json
package.json

ci/cd now runs lint and format checks

cleanup husky hooks

---

CODE_OF_CONDUCT.md

There were grammatical mistakes in the code of conduct file.

Grammatical mistake in the CODE_OF_CONDUCT.md

---

components/team/TeamTab.tsx
lib/env.ts
lib/jackson.ts
lib/jackson/sso.ts
package-lock.json
package.json
pages/api/oauth/authorize.ts
pages/api/oauth/oidc.ts
pages/api/oauth/saml.ts
pages/api/oauth/token.ts
pages/api/teams/[slug]/sso.ts
pages/auth/sso/idp-select.tsx
pages/auth/sso/index.tsx
pages/teams/[slug]/sso.tsx

To be pulled in after https://github.com/boxyhq/ui/pull/647 is released
Changes
- [New] Ability to manage OIDC connections
- Renamed saml endpoints to sso
- Disabled info card in edit view
- Fixed a crash with IdP selection
- Removed zod validation for SSO api endpoints (fully taken care on Jackson end)
- Fixed env sourcing  for `/auth/sso/index.tsx`

OIDC Integration to teams SSO

---

pages/api/teams/[slug]/invitations.ts

This PR addresses a code style issue in the `handlePUT` function within the `invitations.ts` file. Previously, we were using nested if conditions to check if the invitation was sent via email and if the invitation email matches the user's email. However, this can be simplified by merging the nested if conditions into a single condition.
To improve readability, we've updated the `handlePUT` function to merge the nested if conditions.
- Merging the nested if conditions in the `handlePUT` function within `invitations.ts`.
This change should make the code in `invitations.ts` easier to read and maintain.

refactor(invitations): merge nested if conditions in handlePUT function

---

pages/api/teams/[slug]/payments/products.ts

This PR addresses a code style issue in the `products.ts` file. Previously, we were using single-line conditional statements without block braces. However, this can potentially lead to confusion and errors in more complex code.
- Updating the `session.user.id` check in `products.ts` to use block braces for the conditional statement.
This change should make the code in `products.ts` easier to read and maintain.

style(products): use block braces for conditional statements

---

models/user.ts

This PR addresses a code style issue in the `isAllowed` function within the `user.ts` file. Previously, we were using nested if conditions to check the resource and actions. However, this can be simplified by merging the nested if conditions into a single condition.
To improve readability, we've updated the `isAllowed` function to merge the nested if conditions.
- Merging the nested if conditions in the `isAllowed` function within `user.ts`.
This change should make the code in `user.ts` easier to read and maintain.

refactor(user): merge nested if conditions in isAllowed function

---

lib/prisma.ts

This PR addresses a code style issue in the `prisma.ts` file. Previously, we were using single-line conditional statements without block braces. However, this can potentially lead to confusion and errors in more complex code.
- Updating the `NODE_ENV` check in `prisma.ts` to use block braces for the conditional statement.
This change should make the code in `prisma.ts` easier to read and maintain.

style(prisma): use block braces for conditional statements

---

components/team/Members.tsx

This PR addresses a code style issue in the `Members` component. Previously, we were using single-line conditional statements without block braces. However, this can potentially lead to confusion and errors in more complex code.
- Updating the `removeTeamMember` function in `Members.tsx` to use block braces for the `if (!member)` conditional statement.
This change should make the code in `Members` easier to read and maintain.

style(members): use block braces for conditional statements

---

components/apiKey/APIKeys.tsx

This PR addresses a code style issue in the `APIKeys` component. Previously, we were using single-line conditional statements without block braces. However, this can potentially lead to confusion and errors in more complex code.
- Updating the `deleteApiKey` function in `APIKeys.tsx` to use block braces for the `if (!apiKey)` conditional statement.
This change should make the code in `APIKeys` easier to read and maintain.

style(api-keys): use block braces for conditional statements

---

components/shared/shell/Header.tsx

This PR addresses a code style issue in the `Header` component. Previously, we were accessing the `user` property from the `data` object directly. However, using object destructuring can make the code cleaner and easier to understand.
To improve readability, we've updated the code to use object destructuring when accessing the `user` property from the `data` object.
- Updating the `Header` component in `Header.tsx` to use object destructuring for the `data` object.
This change should make the code in `Header` easier to read and maintain.

refactor(header): use object destructuring for session data

---

lib/env.ts

This PR addresses a code style issues in the `env.ts` configuration file. Previously, you were using an unneeded ternary statement to set the flag. However, this can be simplified to a single logical NOT operation.
To improve readability, we've updated the code to avoid the unneeded ternary statement.
- Updating the feature flag in `env.ts` to use a logical NOT operation instead of a ternary statement.
This change should make the code in `env.ts` easier to read and maintain.

refactor(env): simplify ternary statement for dsync feature flag

---

README.md
lib/env.ts

Update README with Detailed Technology Descriptions

docs: Update README with detailed technology descriptions

---

tests/e2e/support/fixtures/api-keys-page.ts
tests/e2e/support/fixtures/join-page.ts
tests/e2e/support/fixtures/settings-page.ts

This change should fix e2e test failure: https://github.com/boxyhq/saas-app/actions/runs/9549314647/job/26320201006?pr=411

E2E fix around strict mode violation

---

lib/svix.ts
pages/api/teams/[slug]/webhooks/index.ts

Automatically create eventTypes if they don't exists

feat: Automatically create eventTypes

---

package-lock.json
package.json

Fixes https://github.com/boxyhq/saas-starter-kit/issues/1772

Added overrides for next-auth and react-email

---

tests/e2e/settings/team-settings.spec.ts
tests/e2e/support/fixtures/sso-page.ts
tests/e2e/support/utils/throttling-network-presets.ts

The page reload causes previous slug to be loaded resulting in test flakiness

Fix e2e flakiness
