components/account/UpdateAccount.tsx

[Issue 417](https://github.com/boxyhq/saas-starter-kit/issues/417)
- In UpdateAccount component:
image: Yup.mixed().required() replaced with Yup.mixed().nullable().test(with the present test) fixed this.

Optional Profile Image

---

components/defaultLanding/FeatureSection.tsx

- have fix the feature gird responsiveness in  large-laptops: (lg) 
- make the grid from 3 col to 2 col for 1280px to 768px
<br/>
<br/>
<br/>

[fix] grid of feature component

---

pages/auth/idp-login.tsx

This PR addresses a code style issue in the `SAMLIdPLogin` function within the `idp-login.tsx` file. Previously, we were using a single-line if statement without block braces. However, this can potentially lead to confusion and errors in more complex code.
To improve readability and maintainability, we've updated the if statement to use block braces. This makes it clear where the conditional code starts and ends, and ensures that we follow best practices for code style.
- Updating the `isReady` check in `SAMLIdPLogin` function within `idp-login.tsx` to use block braces for the if statement.
This change should make the code in `idp-login.tsx` easier to read and maintain.

style(auth): use block braces for if statement in SAMLIdPLogin function

---

pages/api/webhooks/stripe.ts

This PR addresses a code style issue in the `POST` function within the `stripe.ts` file. Previously, we were using a single-line if statement without block braces. However, this can potentially lead to confusion and errors in more complex code.
To improve readability and maintainability, we've updated the if statement to use block braces. This makes it clear where the conditional code starts and ends, and ensures that we follow best practices for code style.
- Updating the `sig` and `webhookSecret` check in `POST` function within `stripe.ts` to use block braces for the if statement.
This change should make the code in `stripe.ts` easier to read and maintain.

style(stripe): use block braces for if statement in POST function

---

pages/api/teams/[slug]/index.ts

This PR addresses a code style issue in the `updateTeam` function within the `index.ts` file. Previously, we were using nested if conditions to check the error type and error code. However, this can be simplified by merging the nested if conditions into a single condition.
To improve readability, we've updated the `updateTeam` function to merge the nested if conditions.
- Merging the nested if conditions in the `updateTeam` function within `index.ts`.
This change should make the code in `index.ts` easier to read and maintain.

refactor(team): merge nested if conditions in updateTeam function

---

pages/api/teams/[slug]/dsync/index.ts

This PR addresses a code style issue in the `index.ts` file. Previously, we were accessing the `body` property from the `req` object directly. However, using object destructuring can make the code cleaner and easier to understand.
To improve readability, we've updated the code to use object destructuring when accessing the `body` property from the `req` object.
- Updating the `index.ts` file to use object destructuring for the `req` object.
This change should make the code in `index.ts` easier to read and maintain.

refactor(dsync): use object destructuring for request body

---

lib/stripe.ts
pages/api/webhooks/stripe.ts

This PR addresses a code style issue in the `stripe.ts` file. Previously, we were using single-line conditional statements without block braces. However, this can potentially lead to confusion and errors in more complex code.
- Updating the `session.user.email` check in `stripe.ts` to use block braces for the conditional statement.
This change should make the code in `stripe.ts` easier to read and maintain.

style(stripe): use block braces for conditional statements

---

lib/nextAuth.ts

This PR addresses a code style issue in the `nextAuth.ts` file. Previously, you were using an unneeded ternary statement to check if `existingUser` exists. However, this can be simplified to a single logical NOT NOT operation.
To improve readability, i have updated the code to avoid the unneeded ternary statement.
- Updating the `existingUser` check in `nextAuth.ts` to use a logical NOT NOT operation instead of a ternary statement.
This change should make the code in `nextAuth.ts` easier to read and maintain.

refactor(auth): simplify ternary statement for existingUser check

---

components/invitation/PendingInvitations.tsx

This PR addresses a code style issue in the `PendingInvitations` component. Previously, we were using single-line conditional statements without block braces. However, this can potentially lead to confusion and errors in more complex code.
- Updating the `deleteInvitation` function in `PendingInvitations.tsx` to use block braces for the `if (!invitation)` conditional statement.
This change should make the code in `PendingInvitations` easier to read and maintain.

style(invitations): use block braces for conditional statements

---

locales/en/common.json
pages/404.tsx
pages/500.tsx

In the course of implementing error pages, I have focused on the 400 and 500 error codes, recognizing the importance of addressing these common issues to enhance user experience. The 404 error page was initially mentioned, but the inclusion of the 500 error page was also considered due to its prevalence in web environments. However, the ability to thoroughly test the 500 error page was limited, as it is a production page, and access to Sentry values was not available. This limitation prevented a comprehensive review and adjustment of the 500 error page.

feat: 404 and 500 error pages

---

lib/rbac.ts
pages/api/teams/[slug]/members.ts

Initially, the objective was to safeguard against the deletion of owner accounts. However, upon further consideration, it was identified that an administrator could circumvent this restriction by altering the role of the owner to either an admin or a user, thereby retaining the ability to delete the owner. To address this vulnerability, the system has been updated to prevent administrators from modifying the role of the owner, thereby enhancing the security measures in place.
Please check.

feat: Implement restrictions: Admins cannot update or delete team owner

---

components/invitation/InviteViaEmail.tsx
components/invitation/InviteViaLink.tsx

This PR fixes an issue where the role dropdown retains the role selected for the previous invitee, leading to potential confusion and incorrect role assignments.
Changes Made:
Added a value attribute to the <select> element to control its value through Formik's state, ensuring the dropdown resets to the default 'Member' role after each invitation.
This update aims to improve user experience by ensuring accurate role assignment.

Fix: Reset Role Dropdown to Default After Invitation

---

lib/rbac.ts
pages/api/teams/[slug]/members.ts

This commit adds validation logic to the `validateMembershipOperation` function in the `rbac.ts` file. The validation ensures that an admin cannot make a member an owner and that a member cannot make someone an admin or owner. This prevents unauthorized role changes within the team membership system.

feat: Add validation for updating member roles

---

delete-team.js

The code changes in this commit add functionality to delete Svix applications. The `delete-team.js` file has been modified to include functions for retrieving and removing Svix applications associated with a team. The `displayDeletionArtifacts` function now checks for Svix applications and displays their details if found. The `handleTeamDeletion` function has been updated to call the new `removeSvixApplication` function to delete the Svix application before removing the team. Additionally, two new helper functions, `getSvixApplication` and `removeSvixApplication`, have been added to handle the retrieval and deletion of Svix applications.

feat: Add Svix application deletion functionality

---

components/team/TeamSettings.tsx

Team name within dropdown should refresh with settings update.

Fix - Refresh teams list dropdown once name is updated

---

pages/api/webhooks/stripe.ts

This commit refactors the code in the `handleSubscriptionUpdated` function in `stripe.ts` to handle subscription updates in the Stripe webhook. It adds a check for the existence of `items` in the event data object and assigns the `priceId` accordingly. The code also updates the Stripe subscription status and other relevant information.

refactor: Handle subscription updates in Stripe webhook

---

instrumentation.ts
next.config.js
sentry.edge.config.ts
sentry.server.config.ts

Sentry was causing issues for `npm run dev` due to some changes in the configuration.
These changes fixes those.

chore: Remove redundant Sentry configurations

---

lib/guards/team-api-key.ts
models/apiKey.ts
pages/api/teams/[slug]/api-keys/[apiKeyId].ts
pages/api/teams/[slug]/webhooks/[endpointId].ts

Adds the `throwIfNoAccessToApiKey` guard function to the `lib/guards/team-api-key.ts` file. This function is responsible for checking if the user has access to the specified API key before performing any actions on it. It throws an `ApiError` with the appropriate status code and error message if the user does not have access.
The guard function is used in the `pages/api/teams/[slug]/api-keys/[apiKeyId].ts` file to ensure that the user has permission to delete the API key before proceeding with the deletion.

feat: Add throwIfNoAccessToApiKey guard function

---

docker-compose.yml

chore: Update docker-compose.yml to remove version field

---

playwright.config.ts

Similar to what we have in Jackson, it makes sense to increase the test timeout to avoid timeouts in CI runs.

Increase e2e test timeout
